# Site settings
title: Rohan and Kate & Co.
email: rohan@rohanandkate.net
url: http://rohanandkate.net
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Rohan &amp; Kate

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/redmeades
    #  - title: blog
    #    url: https://rohan.rohanandkate.net
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/redmeades

# Build settings
markdown: kramdown
permalink: pretty
